### Get all knights

GET http://localhost:8083/api/knights

### Get single knight

GET http://localhost:8083/api/knights/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

### Get single knight - 404 NOT FOUND

GET http://localhost:8083/api/knights/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get order knights

GET http://localhost:8083/api/orders/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/knights

### Get order knights - 404 NOT FOUND

GET http://localhost:8083/api/orders/ac4e2683-b2ba-4695-94d9-806a97fce71e/knights

### Create new knight

PUT http://localhost:8083/api/knights/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Hanz von Hamburg",
  "age": 18,
  "strength": 120,
  "health": 1,
  "order": "5d1da2ae-6a14-4b6d-8b4f-d117867118d4"
}

### Delete knight

DELETE http://localhost:8083/api/knights/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get all orders

GET http://localhost:8083/api/orders

### Get single order

GET http://localhost:8083/api/orders/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Get single order - 404 NOT FOUND

GET http://localhost:8083/api/orders/ac4e2683-b2ba-4695-94d9-806a97fce71e

### Create new order

PUT http://localhost:8083/api/orders/baa5f343-9e5f-4ea1-886e-7c6cd4239d3b
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "The Third Order"
}

### Delete order

DELETE http://localhost:8083/api/orders/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76